name: PR:4.x

on:
  workflow_dispatch:
  pull_request:
    branches:
      - 4.x

jobs:
  Ubuntu2004-ARM64:
    uses: opencv/ci-gha-workflow/.github/workflows/OCV-PR-4.x-ARM64.yaml@main

  Android:
    uses: opencv/ci-gha-workflow/.github/workflows/OCV-PR-4.x-Android.yaml@main

  docs:
    uses: opencv/ci-gha-workflow/.github/workflows/OCV-PR-4.x-docs.yaml@main
