name: PR:4.x

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
    branches:
      - 4.x

concurrency:
  group: OCV-PR-4.x-Android-${{ github.ref }}
  cancel-in-progress: true

env:
  PR_AUTHOR: 'Destiny-HaHa'
  PR_AUTHOR_FORK: 'Destiny-HaHa/opencv'
  SOURCE_BRANCH_NAME: '4.x'
  TARGET_BRANCH_NAME: '4.x'
  GIT_CACHE_DOCKER: '/home/ci/git_cache'
  OPENCV_DOCKER_WORKDIR: "/home/ci/opencv"
  OPENCV_CONTRIB_DOCKER_WORKDIR: "/home/ci/opencv_contrib"
  CCACHE_DIR: '/home/ci/.ccache'

jobs:
  BuildAndTest:
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash
    container:
      image: quay.io/opencv-ci/opencv-androidsdk-30:20231201
    steps:
      - name: Clean
        timeout-minutes: 60
        run: (test -d "${{ env.OPENCV_DOCKER_WORKDIR }}" && find "${{ env.OPENCV_DOCKER_WORKDIR }}" -mindepth 1 -delete) || /bin/true
      - name: Fetch opencv
        timeout-minutes: 60
        run: git clone --branch ${{ env.TARGET_BRANCH_NAME }} https://github.com/opencv/opencv.git ${{ env.OPENCV_DOCKER_WORKDIR }}
      - name: Fetch opencv_contrib
        timeout-minutes: 60
        run: git clone --branch ${{ env.TARGET_BRANCH_NAME }} https://github.com/Destiny-HaHa/opencv_contrib.git ${{ env.OPENCV_CONTRIB_DOCKER_WORKDIR }}
      - name: Build OpenCV for Android SDK
        timeout-minutes: 120
        run: |
          mkdir -p /home/ci/build
          cd /home/ci/build
          sed -i 's+https\\://services.gradle.org/distributions/gradle-@GRADLE_VERSION@-all.zip+file\\:/opt/gradle/gradle-@GRADLE_VERSION@-bin.zip+g' ${{ env.OPENCV_DOCKER_WORKDIR }}/platforms/android/gradle-wrapper/gradle/wrapper/gradle-wrapper.properties.in
          python3 "${{ env.OPENCV_DOCKER_WORKDIR }}/platforms/android/build_sdk.py" --no_kotlin --no_ccache --shared --modules_list "core" --extra_modules_path "${{ env.OPENCV_CONTRIB_DOCKER_WORKDIR }}/modules/" --config "${{ env.OPENCV_DOCKER_WORKDIR }}/platforms/android/ndk-18-api-level-21.config.py" --sdk_path "$ANDROID_HOME" --ndk_path "$ANDROID_NDK_HOME" /home/ci/build
      - name: Create Zip Package
        timeout-minutes: 60
        run: cd /home/ci/build && zip -r -9 OpenCV4Android.zip OpenCV-android-sdk
      - name: Release Zip Package
        timeout-minutes: 60
        uses: actions/upload-artifact@v3
        with:
          name: OpenCV4AndroidSDK.zip
          path: /home/ci/build/OpenCV4Android.zip
      - name: cleanPackage
        timeout-minutes: 60
        run: rm /home/ci/build/OpenCV4Android.zip
      - name: Create 7Zip Package
        uses: DuckSoft/create-7z-action@v1.0
        with:
          pathSource: /home/ci/build/OpenCV-android-sdk/
          pathTarget: /home/ci/build/OpenCV4Android.7z
      - name: Release 7Zip Package
        timeout-minutes: 60
        uses: actions/upload-artifact@v3
        with:
          name: OpenCV4AndroidSDK.7z
          path: /home/ci/build/OpenCV4Android.7z
